### ISSUE TITLE
Register Idea - Attach File/URL

### ISSUE THREAD

**Issue by filhocf** [dataprev/ideax#10]
# Description
* This issue aims to allow a user to link a file or a url to any idea. As a suggestion, in our first version we can allow to attach just a url.

# Project Planning Info
* This Issue is related to WBS's item 1.1.1.1

**Comment by filhocf** [comment]
Can we use a a HTML text editor in order to do this?
As an example, we could use tinymce:

![image](https://user-images.githubusercontent.com/952596/40858161-d1ab5994-65b3-11e8-9b85-8fc0bb724d98.png)

**Comment by filhocf** [comment]
The new version of CKEDITOR looks really powerfull too: https://ckeditor.com/

**Comment by kelvin-neves** [comment]
com a inclusão do editor de markdown essa issue foi solucionada
