### ISSUE TITLE
add Notifications feature

### ISSUE THREAD

**Issue by kelvin-neves** [dataprev/ideax#41]
add notifications feature when idea modifications (phase change, evaluated ..) happen. The suggestion is email, maybe Telegram messages.
This types of notifications needs to be allowed by user through profile preferences.

**Comment by MissHead** [comment]
https://github.com/pinax/pinax-notifications

**Comment by MissHead** [comment]
https://github.com/django-notifications/django-notifications

**Comment by MissHead** [comment]
![image](https://user-images.githubusercontent.com/24864460/51261413-5480e400-1997-11e9-9f79-5bdf03688dee.png)

**Comment by MissHead** [comment]
![image](https://user-images.githubusercontent.com/24864460/51261608-b3def400-1997-11e9-8c12-987a90b13938.png)

**Comment by MissHead** [comment]
![image](https://user-images.githubusercontent.com/24864460/51261651-ca854b00-1997-11e9-99e2-6b9b4670082e.png)

**Comment by MissHead** [comment]
![image](https://user-images.githubusercontent.com/24864460/51261782-11734080-1998-11e9-8570-a490809ae2c4.png)
