### ISSUE TITLE
Add image cropper in Challenge register

### ISSUE THREAD

**Issue by kelvin-neves** [dataprev/ideax#88]
add a image cropper in Challenge register. The suggestion size is 920 x 220. 
Maybe the Cropper.js could help (https://fengyuanchen.github.io/cropperjs/).

**Comment by MissHead** [comment]
![image](https://user-images.githubusercontent.com/24864460/49808121-ed8e6080-fd42-11e8-9cc4-5217f6973f84.png)


![image](https://user-images.githubusercontent.com/24864460/49808175-10207980-fd43-11e8-9195-17e5509680c3.png)

**Comment by MissHead** [comment]
![image](https://user-images.githubusercontent.com/24864460/49808249-4231db80-fd43-11e8-8126-ed76dfd8ac46.png)

**Comment by MissHead** [comment]
![image](https://user-images.githubusercontent.com/24864460/49808322-6b526c00-fd43-11e8-86d8-093aadd66648.png)
